#!/bin/sh

SRC_DIR="org"
DEST_DIR="src/content/docs/notes"
DOCS_ROOT="src/content/docs"

echo "Building notes from $SRC_DIR to $DEST_DIR..."

# 1. Convert/Update existing .org files
find "$SRC_DIR" -type f -name "*.org" | while read -r file; do
    rel_path="${file#$SRC_DIR/}"
    dir_name=$(dirname "$rel_path")
    filename=$(basename "$rel_path" .org)
    
    if [ "$filename" = "how-to-use" ]; then
        # Put how-to-use at the docs root so it's not in the 'Notes' autogenerated sidebar
        mkdir -p "$DOCS_ROOT"
        outfile="$DOCS_ROOT/how-to-use.mdx"
    else
        mkdir -p "$DEST_DIR/$dir_name"
        outfile="$DEST_DIR/$dir_name/$filename.mdx"
    fi
    
    echo "  $file -> $outfile"
    
    # Convert Org to Markdown
    pandoc "$file" -f org -t markdown --mathjax -o "$outfile" --standalone
    
    # Post-process with Node.js
    node scripts/post-process.cjs "$outfile"
done

# 2. Cleanup orphaned .mdx files
echo "Cleaning up orphaned notes..."
# Clean notes subdir
if [ -d "$DEST_DIR" ]; then
    find "$DEST_DIR" -type f -name "*.mdx" | while read -r mdx_file; do
        rel_path="${mdx_file#$DEST_DIR/}"
        org_file="$SRC_DIR/${rel_path%.mdx}.org"
        if [ ! -f "$org_file" ]; then
            echo "  Removing orphaned file: $mdx_file"
            rm "$mdx_file"
        fi
    done
    find "$DEST_DIR" -type d -empty -delete
fi

# Clean docs root orphans (except index.mdx)
find "$DOCS_ROOT" -maxdepth 1 -type f -name "*.mdx" ! -name "index.mdx" | while read -r mdx_file; do
    filename=$(basename "$mdx_file" .mdx)
    org_file="$SRC_DIR/$filename.org"
    if [ ! -f "$org_file" ]; then
        echo "  Removing orphaned root file: $mdx_file"
        rm "$mdx_file"
    fi
done

echo "Done."